apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    # Regla sin host específico - acepta cualquier host (localhost, 127.0.0.1, etc)
    # Útil para Docker Desktop que no resuelve /etc/hosts correctamente
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway-api
                port:
                  number: 80
